# Generated by Django 5.2.6 on 2025-09-14 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_tag_remove_video_comments_video_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dislikes',
            new_name='dislikes_count',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='likes',
            new_name='likes_count',
        ),
        migrations.AlterUniqueTogether(
            name='likesdislaikes',
            unique_together={('video', 'user')},
        ),
    ]
